backend:
  name: github
  repo: wang99404008-proce/Personal_Resume
  branch: main  # 如果你的預設分支是 master 請改成 master
  base_url: https://decap-cms-oauth.vercel.app
  
media_folder: "images"
public_folder: "/images"

collections:
  - name: "resume"
    label: "履歷資料"
    folder: "data"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "姓名", name: "name", widget: "string" }
      - { label: "現任職稱", name: "title", widget: "string" }
      - { label: "個人簡介", name: "bio", widget: "text" }
